spring: 
  application: 
    name: INVENTORY-SERVICE
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'ygz123'
    url: jdbc:mysql://localhost:3307/inventorydb?createDatabaseIfNotExist=true
  jpa:                                          
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
server: 
  port: 8501
